### ISSUE TITLE
Ticker not stopped

### ISSUE THREAD

**Issue by judwhite** [dominikh/go-staticcheck#68] opened 2016-12-30 17:53 UTC
If possible to determine if the ticker / ticker chan doesn't escape the local method (or closure) it should be stopped.

Somewhat interestingly [time.Tick](https://golang.org/pkg/time/#Tick) intentionally allows the ticker to leak for convenience.

**Comment by bradleyfalzon** [comment] 2016-12-30 19:55
Is this a duplicate of SA1015? Or extension of?

**Comment by dominikh** [comment] 2016-12-30 20:08
They're related. One SA1015 is about use of time.Tick, whereas this would be about an actually stoppable ticker that wasn't stopped.

**Closed as completed** 2017-08-02 05:19 UTC
Labels: enhancement
